apiVersion: v1
kind: Service
metadata:
    name: webapp-dev-service
spec:
    selector:
        app: webapp-dev
    type: NodePort
    ports:
        - name: http
          protocol: TCP
          port: 3003
          targetPort: 3003
          nodePort: 32003
